livk:
  postgresql:
    host: livk.com
    port: 5432
    username: postgres
    password: 123456
    database: spring_livk
server:
  port: 9663
spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
