spring:
  shardingsphere:
    datasource:
      names: db0
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://livk.com:3306/sharding_jdbc?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        maxPoolSize: 20
    props:
      sql:
        show: true
    sharding:
      tables:
        sys_log:
          actual-data-nodes: db0.sys_log_$->{2020..2022}_$->{1..12}
          table-strategy:
            standard:
              sharding-column: date
              precise-algorithm-class-name: com.livk.jdbc.config.LivkPreciseShardingAlgorithm

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

server:
  port: 6666
