#tFQTmXNaY5RjDRpxEfsY2lqarQ3xIEFLBiwrulrFKL67Lcunu9PNNgBUVyyu2p6f-m8ZQQH4ZMYfqwX-VVJBrKY83ZRpskTIR4Lb3dhayswBPX5hN-oN6T87k191cn2v


POST localhost:9000/oauth2/token?grant_type=authorization_code&code=SqP8NjQ60nJdZqDxIRo4A5zsp9iyIQ9QOtHfzJBl0HgkXzoUlI8e3ETlpLtAZPYkdr3y5TUdBvlbuQ-PvF4oj1IRvZt_KScX-H1i5DmcKx_RQwmVUZ_NQsfI69pQ4d11&redirect_uri=http://127.0.0.1:9090/oauth2/livk/code/livk-client
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bGl2azpzZWNyZXQ=


###
GET localhost:9000//oauth2/livk/code/livk-client?code=UIcZxnFeCWXpgZRY5TWUvYh5f25HIRu6oIEqeDqppN2IFzDwXtsxcEWQh1VMIA5CyYj7h5Zr8bwyUGgi-c5WeQqHcqVWKkFSTlbBVX2iFn4X3E_cNED2-HymYzdj8sdc
Authorization: Bearer eyJraWQiOiJiMDBmM2EwZi1hYzU1LTRkZWEtOTAwYy00YTg2ODlhODViYjgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsaXZrIiwiYXVkIjoibGl2ayIsImF6cCI6ImxpdmsiLCJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6OTAwMCIsImV4cCI6MTY1MDI3NTU2MywiaWF0IjoxNjUwMjczNzYzfQ.lxL9Vl5Y90sRTTN8En7vToFoC4KyFY29U5ha4h0m18Sg8G3oGnVky6u-J8bZdGSNBejdI41zBYPZFpLFQF7Ny1fcpjACuQR_KcA2aXwI6TkpBIEs85C_TkiN-IoacCkBb3cT6Zc3kYJNguVtrnRjZ_eWQPWAUtGW1WxGZ9qXsGj2v3zh4lBXQOgZXAOrjVJLNwgUaTerl2lToAMvJkOVwwE7-8ZTvJgTXMSmHEkMudU-yvBCKLSPLHsGhbEezTZMX2x9sH6xWOUEHmcbozX2YzFc2MN1Su_KJlQFt4Nc08Faaxen_zIG9Dhg7EFesME1H4YICx8pqt-rKetFt9kN_Q
